# GoReleaser configuration for Go library
version: 2

before:
  hooks:
    - go mod tidy

# No builds section for libraries - they are distributed via go get

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
  groups:
    - title: 'Features'
      regexp: '^.*?feat.*?:'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix.*?:'
      order: 1
    - title: 'Others'
      order: 999
