# GoReleaser configuration for Go library
# Make sure to check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    - go mod tidy
    - go test -v ./...

# Explicitly disable builds for libraries
builds:
  - skip: true

# Source distribution for libraries
source:
  enabled: true

checksum:
  name_template: 'checksums.txt'
  
changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
      
sboms:
  - artifacts: source
