project_name: test-library

before:
  hooks:
    - go mod tidy

# Pour une bibliothèque, nous ne construisons pas de binaires

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

snapshot:
  name_template: "{{ incpatch .Version }}-next"

# Configuration spécifique pour les bibliothèques distribuées
gomod:
  proxy: true

# Configuration pour publier sur les dépôts Go
release:
  github:
    owner: Ange-Cesari
    name: test-library
  draft: false
  prerelease: auto

# Enable Go modules publishing
# No goreportcard announce as it's not supported in this version
