project_name: test-library

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/test-library
    ldflags:
      - -s -w
      - -X main.Version={{ .Version }}
      - -X main.CommitSHA={{ .Commit }}
      - -X main.BuildDate={{ .Date }}
    binary: test-library

archives:
  - format: tar.gz
    name_template: "test-library_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      # LICENSE file is optional but recommended
      # - LICENSE
      # Documentation directory is optional
      # - docs/*

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

sboms:
  - id: test-library-sbom
    artifacts: binary
    documents:
      - "test-library_{{ .Version }}_{{ .Os }}_{{ .Arch }}_sbom.spdx.json"
