# GoReleaser configuration for Go library
version: 2

# This is a library project, so we disable all builds
# https://goreleaser.com/customization/build/
builds:
  - binary: fake-binary-name
    goos: [linux]
    goarch: [amd64]
    skip: true
    main: ./examples

before:
  hooks:
    - go mod tidy

# We don't want any archives for libraries
archives:
  - format: binary
    files: [none]

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
  groups:
    - title: 'Features'
      regexp: '^.*?feat.*?:'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix.*?:'
      order: 1
    - title: 'Others'
      order: 999
