project_name: test-library
project_type: library
language: go
platforms:
    - linux
    - darwin
    - windows
architectures: []
release_assets:
    - checksum
    - source
    - sbom
ci_provider: github
