version: '3'

vars:
  BINARY_NAME: test-library
  VERSION:
    sh: git describe --tags --always --dirty
  COMMIT:
    sh: git rev-parse --short HEAD
  DATE:
    sh: date -u '+%Y-%m-%d_%H:%M:%S'
  BUILD_DIR: dist
  BUILD_FLAGS: -ldflags "-s -w -X main.Version={{.VERSION}} -X main.CommitSHA={{.COMMIT}} -X main.BuildDate={{.DATE}}"
  MAIN_PACKAGE: ./pkg/test-library

tasks:

  build-windows-arm64:
    desc: Build for windows/arm64
    cmds:
      - go build -o {{.BINARY_NAME}}-windows-arm64 {{.MAIN_PACKAGE}}
    env:
      GOOS: windows
      GOARCH: arm64
    generates:
      - {{.BINARY_NAME}}-windows-arm64{{exeExt}}

  build-darwin-arm64:
    desc: Build for darwin/arm64
    cmds:
      - go build -o {{.BINARY_NAME}}-darwin-arm64 {{.MAIN_PACKAGE}}
    env:
      GOOS: darwin
      GOARCH: arm64
    generates:
      - {{.BINARY_NAME}}-darwin-arm64{{exeExt}}

  build-windows-amd64:
    desc: Build for windows/amd64
    cmds:
      - go build -o {{.BINARY_NAME}}-windows-amd64 {{.MAIN_PACKAGE}}
    env:
      GOOS: windows
      GOARCH: amd64
    generates:
      - {{.BINARY_NAME}}-windows-amd64{{exeExt}}

  build-darwin-amd64:
    desc: Build for darwin/amd64
    cmds:
      - go build -o {{.BINARY_NAME}}-darwin-amd64 {{.MAIN_PACKAGE}}
    env:
      GOOS: darwin
      GOARCH: amd64
    generates:
      - {{.BINARY_NAME}}-darwin-amd64{{exeExt}}

  build-linux-amd64:
    desc: Build for linux/amd64
    cmds:
      - go build -o {{.BINARY_NAME}}-linux-amd64 {{.MAIN_PACKAGE}}
    env:
      GOOS: linux
      GOARCH: amd64
    generates:
      - {{.BINARY_NAME}}-linux-amd64{{exeExt}}
  build:
    desc: Build for the current platform
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build {{.BUILD_FLAGS}} -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PACKAGE}}

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  lint:
    desc: Run linters
    cmds:
      - go vet ./...
      - |
        if ! command -v golangci-lint &> /dev/null; then
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        fi
      - golangci-lint run

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - mkdir -p {{.BUILD_DIR}}

  
