name: CI

on:
  push:
    branches: [develop, main, 'feature/*', 'release/*']
  pull_request:
    branches: [develop, main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Check out code
        uses: actions/checkout@v4
        
      
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: '3.x'
          repo-token: $${{ secrets.GITHUB_TOKEN }}
          
      - name: Install dependencies
        run: go mod download
        
      - name: Lint
        run: task lint
        
      - name: Test
        run: task test
        
      - name: Build
        run: task build
      
